import Head from "next/head";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<hr />
			<div>
				<h2> Hello this is a Next js website </h2>
			</div>
		</div>
	);
}
